spring:
  security:
    oauth2:
      client:
        registration:
          # 구글 로그인 추가
          google:
            client-id: 461003405923-ho37jug7rrms976d23qk1eivi2san0i5.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile